import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#5ff3e8",
        "primary-container": "#39d6cc",
        "on-primary": "#003734",
        "on-primary-container": "#005954",
        "primary-fixed": "#66f8ee",
        "primary-fixed-dim": "#41dcd1",
        "on-primary-fixed": "#00201e",
        "on-primary-fixed-variant": "#00504c",
        "inverse-primary": "#006a65",

        secondary: "#d2bbff",
        "secondary-container": "#6001d1",
        "on-secondary": "#3f008e",
        "on-secondary-container": "#c9aeff",
        "secondary-fixed": "#eaddff",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed": "#25005a",
        "on-secondary-fixed-variant": "#5a00c6",

        tertiary: "#ffd6ad",
        "tertiary-container": "#ffb156",
        "on-tertiary": "#482900",
        "on-tertiary-container": "#734400",
        "tertiary-fixed": "#ffdcbb",
        "tertiary-fixed-dim": "#ffb869",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#673d00",

        background: "#050505",
        "on-background": "#dde4e2",

        surface: "#0e1514",
        "surface-dim": "#0e1514",
        "surface-bright": "#343b3a",
        "surface-container-lowest": "#090f0f",
        "surface-container-low": "#161d1c",
        "surface-container": "#1a2120",
        "surface-container-high": "#242b2a",
        "surface-container-highest": "#2f3635",
        "surface-variant": "#2f3635",
        "surface-tint": "#41dcd1",
        "on-surface": "#dde4e2",
        "on-surface-variant": "#bbcac7",
        "inverse-surface": "#dde4e2",
        "inverse-on-surface": "#2b3231",

        outline: "#859491",
        "outline-variant": "#3c4948",

        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1280px",
      },
      fontFamily: {
        display: ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        headline: ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        body: ["var(--font-geist)", "Geist", "sans-serif"],
        "body-md": ["var(--font-geist)", "Geist", "sans-serif"],
        "body-lg": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-md": ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        "display-lg": ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        "display-xl": ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        "label-caps": ["var(--font-geist)", "Geist", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["84px", { lineHeight: "90%", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg": ["64px", { lineHeight: "100%", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "120%", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "160%", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "160%", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "100%", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      boxShadow: {
        "glow-primary": "0 0 40px rgba(95, 243, 232, 0.4)",
        "glow-primary-lg": "0 0 60px rgba(95, 243, 232, 0.6)",
        "glow-secondary": "0 0 40px rgba(210, 187, 255, 0.35)",
        "glow-subtle": "0 0 25px rgba(95, 243, 232, 0.2)",
      },
    },
  },
  plugins: [],
};

export default config;
