import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#5ff3e8",
        "primary-container": "#39d6cc",
        "on-primary": "#003734",
        "on-primary-container": "#005954",
        "primary-fixed": "#66f8ee",
        "primary-fixed-dim": "#41dcd1",
        "on-primary-fixed": "#00201e",
        "on-primary-fixed-variant": "#00504c",
        "inverse-primary": "#006a65",

        secondary: "#d2bbff",
        "secondary-container": "#6001d1",
        "on-secondary": "#3f008e",
        "on-secondary-container": "#c9aeff",
        "secondary-fixed": "#eaddff",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed": "#25005a",
        "on-secondary-fixed-variant": "#5a00c6",

        tertiary: "#ffd6ad",
        "tertiary-container": "#ffb156",
        "on-tertiary": "#482900",
        "on-tertiary-container": "#734400",
        "tertiary-fixed": "#ffdcbb",
        "tertiary-fixed-dim": "#ffb869",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#673d00",

        background: "#050505",
        "on-background": "#dde4e2",

        surface: "#0e1514",
        "surface-dim": "#0e1514",
        "surface-bright": "#343b3a",
        "surface-container-lowest": "#090f0f",
        "surface-container-low": "#161d1c",
        "surface-container": "#1a2120",
        "surface-container-high": "#242b2a",
        "surface-container-highest": "#2f3635",
        "surface-variant": "#2f3635",
        "surface-tint": "#41dcd1",
        "on-surface": "#dde4e2",
        "on-surface-variant": "#bbcac7",
        "inverse-surface": "#dde4e2",
        "inverse-on-surface": "#2b3231",

        outline: "#859491",
        "outline-variant": "#3c4948",

        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",

        // Stitch Design System - Luxury Theme additions
        gold: {
          DEFAULT: "#c5a059",
          50: "#faf6ed",
          100: "#f4ead2",
          200: "#e9c176",
          300: "#fed488",
          400: "#c5a059",
          500: "#775a19",
          600: "#5d4201",
          700: "#261900",
        },
        navy: {
          DEFAULT: "#0a192f",
          900: "#060d18",
          800: "#0a192f",
          700: "#0d1c32",
          600: "#132742",
          500: "#1b3a61",
        },
        cream: {
          DEFAULT: "#f9f6f0",
          50: "#ffffff",
          100: "#fbf9f8",
          200: "#f5f3f3",
          300: "#efeded",
          400: "#eae8e7",
          500: "#e4e2e2",
          600: "#dbd9d9",
        },
        cyan: {
          DEFAULT: "#4bfcde",
          glow: "rgba(79, 255, 225, 0.15)",
          bright: "#5ff3e8",
          dark: "#007162",
        },
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "section-gap": "64px",
        "container-padding": "24px",
      },
      fontFamily: {
        display: ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        headline: ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        body: ["var(--font-geist)", "Geist", "sans-serif"],
        "body-md": ["Montserrat", "var(--font-geist)", "Geist", "sans-serif"],
        "body-lg": ["Montserrat", "var(--font-geist)", "Geist", "sans-serif"],
        "headline-md": ["Playfair Display", "var(--font-bricolage)", "serif"],
        "headline-lg": ["Playfair Display", "var(--font-bricolage)", "serif"],
        "headline-lg-mobile": ["Playfair Display", "var(--font-bricolage)", "serif"],
        "display-lg": ["Playfair Display", "var(--font-bricolage)", "serif"],
        "display-xl": ["Playfair Display", "var(--font-bricolage)", "serif"],
        "label-caps": ["Montserrat", "var(--font-geist)", "sans-serif"],
        "label-sm": ["Montserrat", "var(--font-geist)", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "serif"],
        sans: ["Montserrat", "Inter", "var(--font-geist)", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        playfair: ["Playfair Display", "serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["84px", { lineHeight: "90%", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "100%", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      boxShadow: {
        "glow-primary": "0 0 40px rgba(95, 243, 232, 0.4)",
        "glow-primary-lg": "0 0 60px rgba(95, 243, 232, 0.6)",
        "glow-secondary": "0 0 40px rgba(210, 187, 255, 0.35)",
        "glow-gold": "0 0 30px rgba(197, 160, 89, 0.35)",
        "glow-gold-lg": "0 0 50px rgba(197, 160, 89, 0.5)",
        "glow-cyan": "0 0 30px rgba(75, 252, 222, 0.35)",
        "glow-subtle": "0 0 25px rgba(95, 243, 232, 0.2)",
      },
    },
  },
  plugins: [],
};

export default config;
