import { Member } from "@/types/member";
import { JoinRequest } from "@/types/joinRequest";
import { Todo } from "@/types/todo";
import { ClubEvent } from "@/types/event";
import { AppNotification } from "@/types/notification";
import { ActivityLog } from "@/types/activity";

export const INITIAL_MEMBERS: Member[] = [
  {
    uid: "admin_uid_alex",
    name: "Alex Mercer",
    email: "alex@disenodivino.org",
    loginEmail: "alex@disenodivino.org",
    usn: "1DD23CS001",
    semester: "6th Semester",
    branch: "Computer Science & Engineering",
    domain: "UI/UX",
    role: "admin",
    status: "active",
    joinedAt: "2023-08-15T10:00:00.000Z",
    bio: "Design Lead & Full Stack Architect at Diseño Divino. Passionate about neo-brutalism and generative 3D web interfaces.",
    github: "https://github.com/alexmercer",
    linkedin: "https://linkedin.com/in/alexmercer",
    portfolio: "https://alexmercer.design",
    permissions: {
      reviewRequests: true,
      manageRequests: true,
      assignTodos: true,
      manageMembers: true,
      createEvents: true,
    },
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAJrYAyP3yAkjK40F8vW7_bnmRsxSat4bW1stLCn_KEu-9OXay9v9Ih--zJlbwK3V1WWGe9wkhuL040wMmqdFPUyf4c-FXrU1fHzKnI6UMfs2wQ7l0-kDXJzCHKrPF_ftmTZNTaVfDXjobsKO3j7XqjlifIaqOCAhuedLQJZkZ9V2_JpmR9kyaACfFb2SuEUMeN9hF8rxleCZTXkkQpQN0vBvFE70kz4fJ3Ipg7UQNiw74toLZTcGwU",
  },
  {
    uid: "member_uid_jane",
    name: "Jane Doe",
    email: "jane@disenodivino.org",
    loginEmail: "jane@disenodivino.org",
    usn: "1DD23IS042",
    semester: "4th Semester",
    branch: "Information Science",
    domain: "UI/UX",
    role: "member",
    status: "active",
    joinedAt: "2023-09-01T14:30:00.000Z",
    bio: "UI/UX enthusiast focused on interactive micro-animations and accessible design systems.",
    permissions: {
      reviewRequests: true,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },
  {
    uid: "member_uid_alex_chen",
    name: "Alex Chen",
    email: "chen@disenodivino.org",
    loginEmail: "chen@disenodivino.org",
    usn: "1DD23CS019",
    semester: "4th Semester",
    branch: "Computer Science",
    domain: "Tech",
    role: "member",
    status: "active",
    joinedAt: "2023-09-10T11:00:00.000Z",
    bio: "Creative developer experimenting with Three.js, WebGL shaders, and Next.js.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAJrYAyP3yAkjK40F8vW7_bnmRsxSat4bW1stLCn_KEu-9OXay9v9Ih--zJlbwK3V1WWGe9wkhuL040wMmqdFPUyf4c-FXrU1fHzKnI6UMfs2wQ7l0-kDXJzCHKrPF_ftmTZNTaVfDXjobsKO3j7XqjlifIaqOCAhuedLQJZkZ9V2_JpmR9kyaACfFb2SuEUMeN9hF8rxleCZTXkkQpQN0vBvFE70kz4fJ3Ipg7UQNiw74toLZTcGwU",
  },
  {
    uid: "member_uid_sarah",
    name: "Sarah Miller",
    email: "sarah@disenodivino.org",
    loginEmail: "sarah@disenodivino.org",
    usn: "1DD23AI015",
    semester: "4th Semester",
    branch: "AI & Machine Learning",
    domain: "Graphics",
    role: "member",
    status: "active",
    joinedAt: "2023-10-05T09:15:00.000Z",
    bio: "3D artist and brand designer. Blender, Spline, and Figma explorer.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: true,
    },
  },
  {
    uid: "member_uid_rahul",
    name: "Rahul J",
    email: "rahul@disenodivino.org",
    loginEmail: "rahul@disenodivino.org",
    usn: "1DD23EC088",
    semester: "6th Semester",
    branch: "Electronics & Communication",
    domain: "Operations",
    role: "member",
    status: "active",
    joinedAt: "2023-08-20T16:45:00.000Z",
    bio: "Operations lead managing logistics, campus sponsorships, and venue setups.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },
  {
    uid: "member_uid_elena",
    name: "Elena Rodriguez",
    email: "elena@disenodivino.org",
    loginEmail: "elena@disenodivino.org",
    usn: "1DD22CS034",
    semester: "8th Semester",
    branch: "Computer Science",
    domain: "Social Media",
    role: "member",
    status: "active",
    joinedAt: "2022-11-12T12:00:00.000Z",
    bio: "Content creator and social strategist for Diseño Divino.",
    permissions: {
      reviewRequests: true,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBZJZbT3ErTFZEvO1lZL_QKItv8NcDK7AixmW-BKvZ7u_ucPe7MO4Fem3hYhNwyys5Z1KSMgJScoG3u0zxgr8ayIacckpYWK9GKylW19x6xxU3jrC7idvzzBF_hnuqiU6rnyK3Pw1IDa-N5jXzZfYxqjwZnA20dAE3aAkx8MRS59rN8Gqea1nEsb4-slttkXOsD9bw-bvrZ_FVLMVZtsDI3IOSFULLrudNH75yCk943lPwLLcuSIi0l",
  },
];

export const INITIAL_JOIN_REQUESTS: JoinRequest[] = [
  {
    id: "req_001",
    name: "Alex Rivera",
    email: "alex.rivera@college.edu",
    semester: "3rd Semester",
    branch: "Computer Science",
    usn: "1DD24CS012",
    domain: "UI/UX",
    workLink: "https://www.behance.net/alexrivera_design",
    status: "pending",
    submittedAt: "2026-08-27T18:30:00.000Z",
    notes: "Strong portfolio in mobile app design and wireframing.",
  },
  {
    id: "req_002",
    name: "Elena Rostova",
    email: "elena.r@college.edu",
    semester: "5th Semester",
    branch: "Information Science",
    usn: "1DD23IS055",
    domain: "Tech",
    workLink: "https://github.com/elenarostova",
    status: "pending",
    submittedAt: "2026-08-27T16:15:00.000Z",
    notes: "Experience with React, Tailwind, and WebGL.",
  },
  {
    id: "req_003",
    name: "Sam Taylor",
    email: "sam.taylor@college.edu",
    semester: "3rd Semester",
    branch: "Electronics",
    usn: "1DD24EC078",
    domain: "Graphics",
    workLink: "https://dribbble.com/samtaylordesign",
    status: "pending",
    submittedAt: "2026-08-27T14:00:00.000Z",
    notes: "Branding and digital illustration background.",
  },
  {
    id: "req_004",
    name: "Marcus Vance",
    email: "marcus.v@college.edu",
    semester: "5th Semester",
    branch: "Mechanical",
    usn: "1DD23ME022",
    domain: "Social Media",
    workLink: "https://instagram.com/marcus_creates",
    status: "pending",
    submittedAt: "2026-08-26T20:00:00.000Z",
  },
  {
    id: "req_005",
    name: "Priya Sharma",
    email: "priya.s@college.edu",
    semester: "3rd Semester",
    branch: "Computer Science",
    usn: "1DD24CS089",
    domain: "PR / Marketing & Sponsorship",
    workLink: "https://linkedin.com/in/priyasharma_pr",
    status: "pending",
    submittedAt: "2026-08-26T15:40:00.000Z",
  },
  {
    id: "req_006",
    name: "Karan Mehta",
    email: "karan.m@college.edu",
    semester: "5th Semester",
    branch: "Civil",
    usn: "1DD23CV011",
    domain: "Operations",
    workLink: "https://drive.google.com/file/d/sample-resume",
    status: "pending",
    submittedAt: "2026-08-25T11:20:00.000Z",
  },
];

export const INITIAL_TODOS: Todo[] = [
  {
    id: "todo_001",
    text: "Submit high-fidelity wireframes for Design Sprint v2",
    assignedTo: "admin_uid_alex",
    assignedToName: "Alex Mercer",
    createdBy: "admin_uid_alex",
    createdByName: "Alex Mercer",
    completed: false,
    dueDate: "Due Today, 11:59 PM",
    createdAt: "2026-08-27T10:00:00.000Z",
  },
  {
    id: "todo_002",
    text: "Review portfolio submissions for Tech & UI/UX domains",
    assignedTo: "admin_uid_alex",
    assignedToName: "Alex Mercer",
    createdBy: "admin_uid_alex",
    createdByName: "Alex Mercer",
    completed: false,
    dueDate: "Due Tomorrow",
    createdAt: "2026-08-27T11:30:00.000Z",
  },
  {
    id: "todo_003",
    text: "Coordinate workshop setup in Design Lab 404",
    assignedTo: "member_uid_rahul",
    assignedToName: "Rahul J",
    createdBy: "admin_uid_alex",
    createdByName: "Alex Mercer",
    completed: false,
    dueDate: "March 15",
    createdAt: "2026-08-26T14:00:00.000Z",
  },
  {
    id: "todo_004",
    text: "Design promotional banners for Race to Innovate 2.0",
    assignedTo: "member_uid_sarah",
    assignedToName: "Sarah Miller",
    createdBy: "admin_uid_alex",
    createdByName: "Alex Mercer",
    completed: true,
    completedAt: "2026-08-26T18:00:00.000Z",
    dueDate: "Yesterday",
    createdAt: "2026-08-25T09:00:00.000Z",
  },
];

export const INITIAL_EVENTS: ClubEvent[] = [
  {
    id: "event_001",
    name: "Race to Innovate 2.0",
    description: "Anaadyanta Geekmayhem 2026 — 24-hour UI/UX & Creative Tech Hackathon. Compete in teams to solve real-world campus & product design challenges.",
    date: "March 20, 2026",
    time: "09:00 AM - 09:00 AM (24h)",
    location: "Main Auditorium & Design Lab",
    category: "Hackathon",
    status: "active",
    rsvpCount: 142,
    createdAt: "2026-08-20T10:00:00.000Z",
    createdBy: "admin_uid_alex",
  },
  {
    id: "event_002",
    name: "UI/UX Masterclass: Glassmorphism & Neo-Brutalism",
    description: "Deep dive into atmospheric depth, lighting sources in dark mode, and crafting responsive design systems in Figma and React.",
    date: "April 12, 2026",
    time: "14:00 - 17:00",
    location: "Design Lab 404",
    category: "Workshop",
    status: "active",
    rsvpCount: 88,
    createdAt: "2026-08-22T14:30:00.000Z",
    createdBy: "admin_uid_alex",
  },
  {
    id: "event_003",
    name: "Creative Coding Jam: Shaders & Three.js",
    description: "Hands-on session building generative 3D interactive graphics for modern websites.",
    date: "May 24, 2026",
    time: "16:00 - 19:00",
    location: "Computer Center 2",
    category: "Coding Jam",
    status: "active",
    rsvpCount: 64,
    createdAt: "2026-08-25T08:00:00.000Z",
    createdBy: "admin_uid_alex",
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif_001",
    recipientUid: "admin_uid_alex",
    title: "New Join Request",
    message: "Alex Rivera submitted an application for the UI/UX Design domain.",
    type: "request",
    read: false,
    createdAt: "2026-08-27T18:30:00.000Z",
    link: "/dashboard/requests",
  },
  {
    id: "notif_002",
    recipientUid: "admin_uid_alex",
    title: "New To-Do Assigned",
    message: "You have an open task: 'Submit high-fidelity wireframes for Design Sprint v2'",
    type: "todo",
    read: false,
    createdAt: "2026-08-27T10:00:00.000Z",
    link: "/dashboard/todos",
  },
  {
    id: "notif_003",
    recipientUid: "admin_uid_alex",
    title: "New Club Event",
    message: "Race to Innovate 2.0 has been scheduled for March 2026. Review registrations.",
    type: "event",
    read: true,
    createdAt: "2026-08-26T09:00:00.000Z",
    link: "/dashboard/events",
  },
];

export const INITIAL_ACTIVITY: ActivityLog[] = [
  {
    id: "act_001",
    action: "Application submitted",
    performedBy: "Alex Rivera",
    performedByName: "Alex Rivera",
    target: "UI/UX Domain",
    details: "New applicant for 3rd Semester",
    createdAt: "2026-08-27T18:30:00.000Z",
  },
  {
    id: "act_002",
    action: "To-Do assigned",
    performedBy: "admin_uid_alex",
    performedByName: "Alex Mercer",
    target: "Rahul J",
    details: "Assigned 'Coordinate workshop setup in Design Lab 404'",
    createdAt: "2026-08-26T14:00:00.000Z",
  },
  {
    id: "act_003",
    action: "Event created",
    performedBy: "admin_uid_alex",
    performedByName: "Alex Mercer",
    target: "Race to Innovate 2.0",
    details: "Published 24-hour design hackathon",
    createdAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "act_004",
    action: "Member created",
    performedBy: "admin_uid_alex",
    performedByName: "Alex Mercer",
    target: "Alex Chen",
    details: "Added to Tech Domain as Core Member",
    createdAt: "2023-09-10T11:00:00.000Z",
  },
];
