import { Member } from "@/types/member";
import { JoinRequest } from "@/types/joinRequest";
import { Todo } from "@/types/todo";
import { ClubEvent } from "@/types/event";
import { AppNotification } from "@/types/notification";
import { ActivityLog } from "@/types/activity";

export const SEED_MEMBERS: Member[] = [
  // 1. UI/UX Domain (2 members)
  {
    uid: "admin_uid_jeevan",
    name: "Jeevan (Admin)",
    email: "jeevan@gmail.com",
    loginEmail: "jeevan@gmail.com",
    usn: "1DD23CS001",
    semester: "6th Semester",
    branch: "Computer Science & Engineering",
    domain: "UI/UX",
    role: "admin",
    status: "active",
    joinedAt: "2023-08-15T10:00:00.000Z",
    bio: "Lead Administrator & UI/UX Architect at Diseño Divino. Overseeing club operations, design systems, and tech integration.",
    github: "https://github.com/jeevan-dd",
    linkedin: "https://linkedin.com/in/jeevan-admin",
    portfolio: "https://disenodivino.org",
    permissions: {
      reviewRequests: true,
      manageRequests: true,
      assignTodos: true,
      manageMembers: true,
      createEvents: true,
    },
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAJrYAyP3yAkjK40F8vW7_bnmRsxSat4bW1stLCn_KEu-9OXay9v9Ih--zJlbwK3V1WWGe9wkhuL040wMmqdFPUyf4c-FXrU1fHzKnI6UMfs2wQ7l0-kDXJzCHKrPF_ftmTZNTaVfDXjobsKO3j7XqjlifIaqOCAhuedLQJZkZ9V2_JpmR9kyaACfFb2SuEUMeN9hF8rxleCZTXkkQQN0vBvFE70kz4fJ3Ipg7UQNiw74toLZTcGwU",
  },
  {
    uid: "mem_uiux_jane",
    name: "Jane Doe",
    email: "jane@disenodivino.org",
    loginEmail: "jane@disenodivino.org",
    usn: "1DD23IS042",
    semester: "4th Semester",
    branch: "Information Science",
    domain: "UI/UX",
    role: "member",
    status: "active",
    joinedAt: "2023-09-01T14:30:00.000Z",
    bio: "UI/UX enthusiast focused on interactive micro-animations and accessible design systems.",
    permissions: {
      reviewRequests: true,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },

  // 2. Tech Domain (2 members)
  {
    uid: "mem_tech_praveen",
    name: "Praveen",
    email: "praveen@gmail.com",
    loginEmail: "praveen@gmail.com",
    usn: "1DD23CS045",
    semester: "4th Semester",
    branch: "Computer Science",
    domain: "Tech",
    role: "member",
    status: "active",
    joinedAt: "2023-09-05T10:00:00.000Z",
    bio: "Full Stack Developer at Diseño Divino specializing in Next.js, TypeScript, and Firebase cloud integrations.",
    github: "https://github.com/praveen-dd",
    linkedin: "https://linkedin.com/in/praveen-tech",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },
  {
    uid: "mem_tech_alex_chen",
    name: "Alex Chen",
    email: "chen@disenodivino.org",
    loginEmail: "chen@disenodivino.org",
    usn: "1DD23CS019",
    semester: "4th Semester",
    branch: "Computer Science",
    domain: "Tech",
    role: "member",
    status: "active",
    joinedAt: "2023-09-10T11:00:00.000Z",
    bio: "Creative developer experimenting with Three.js, WebGL shaders, and Next.js.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },

  // 3. Graphics Domain (2 members)
  {
    uid: "mem_gfx_sarah",
    name: "Sarah Miller",
    email: "sarah@disenodivino.org",
    loginEmail: "sarah@disenodivino.org",
    usn: "1DD23AI015",
    semester: "4th Semester",
    branch: "AI & Machine Learning",
    domain: "Graphics",
    role: "member",
    status: "active",
    joinedAt: "2023-10-05T09:15:00.000Z",
    bio: "3D artist and brand designer. Blender, Spline, and Figma visualizer.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: true,
    },
  },
  {
    uid: "mem_gfx_sam",
    name: "Sam Taylor",
    email: "sam.taylor@disenodivino.org",
    loginEmail: "sam.taylor@disenodivino.org",
    usn: "1DD24EC078",
    semester: "2nd Semester",
    branch: "Electronics & Communication",
    domain: "Graphics",
    role: "member",
    status: "active",
    joinedAt: "2024-01-15T12:00:00.000Z",
    bio: "Vector illustrator and motion graphics artist creating visual identities for club events.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },

  // 4. Social Media Domain (2 members)
  {
    uid: "mem_social_elena",
    name: "Elena Rodriguez",
    email: "elena@disenodivino.org",
    loginEmail: "elena@disenodivino.org",
    usn: "1DD22CS034",
    semester: "8th Semester",
    branch: "Computer Science",
    domain: "Social Media",
    role: "member",
    status: "active",
    joinedAt: "2022-11-12T12:00:00.000Z",
    bio: "Content creator and social strategist for Diseño Divino.",
    permissions: {
      reviewRequests: true,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },
  {
    uid: "mem_social_marcus",
    name: "Marcus Vance",
    email: "marcus@disenodivino.org",
    loginEmail: "marcus@disenodivino.org",
    usn: "1DD23ME022",
    semester: "6th Semester",
    branch: "Mechanical Engineering",
    domain: "Social Media",
    role: "member",
    status: "active",
    joinedAt: "2023-08-25T15:00:00.000Z",
    bio: "Short-form video director and digital campaigns lead across campus networks.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },

  // 5. PR / Marketing & Sponsorship Domain (2 members)
  {
    uid: "mem_pr_priya",
    name: "Priya Sharma",
    email: "priya@disenodivino.org",
    loginEmail: "priya@disenodivino.org",
    usn: "1DD24CS089",
    semester: "4th Semester",
    branch: "Computer Science",
    domain: "PR / Marketing & Sponsorship",
    role: "member",
    status: "active",
    joinedAt: "2023-09-15T11:00:00.000Z",
    bio: "Corporate outreach coordinator securing sponsorships and industry speaker partnerships.",
    permissions: {
      reviewRequests: true,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },
  {
    uid: "mem_pr_aryan",
    name: "Aryan Verma",
    email: "aryan@disenodivino.org",
    loginEmail: "aryan@disenodivino.org",
    usn: "1DD23IS033",
    semester: "4th Semester",
    branch: "Information Science",
    domain: "PR / Marketing & Sponsorship",
    role: "member",
    status: "active",
    joinedAt: "2023-10-01T14:20:00.000Z",
    bio: "Public relations and inter-college event promotion specialist.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },

  // 6. Operations Domain (2 members)
  {
    uid: "mem_ops_rahul",
    name: "Rahul J",
    email: "rahul@disenodivino.org",
    loginEmail: "rahul@disenodivino.org",
    usn: "1DD23EC088",
    semester: "6th Semester",
    branch: "Electronics & Communication",
    domain: "Operations",
    role: "member",
    status: "active",
    joinedAt: "2023-08-20T16:45:00.000Z",
    bio: "Operations lead managing logistics, campus sponsorships, and venue setups.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },
  {
    uid: "mem_ops_ananya",
    name: "Ananya Roy",
    email: "ananya@disenodivino.org",
    loginEmail: "ananya@disenodivino.org",
    usn: "1DD23CV011",
    semester: "6th Semester",
    branch: "Civil Engineering",
    domain: "Operations",
    role: "member",
    status: "active",
    joinedAt: "2023-09-02T13:10:00.000Z",
    bio: "Resource allocation and event day schedule coordinator.",
    permissions: {
      reviewRequests: false,
      manageRequests: false,
      assignTodos: false,
      manageMembers: false,
      createEvents: false,
    },
  },
];

export const SEED_JOIN_REQUESTS: JoinRequest[] = [
  {
    id: "req_seed_001",
    name: "Alex Rivera",
    email: "alex.rivera@college.edu",
    semester: "3rd Semester",
    branch: "Computer Science",
    usn: "1DD24CS012",
    domain: "UI/UX",
    workLink: "https://www.behance.net/alexrivera_design",
    status: "pending",
    submittedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    notes: "Strong portfolio in mobile app design and wireframing.",
  },
  {
    id: "req_seed_002",
    name: "Elena Rostova",
    email: "elena.r@college.edu",
    semester: "5th Semester",
    branch: "Information Science",
    usn: "1DD23IS055",
    domain: "Tech",
    workLink: "https://github.com/elenarostova",
    status: "pending",
    submittedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    notes: "Experience with React, Tailwind, and WebGL.",
  },
  {
    id: "req_seed_003",
    name: "Karan Mehta",
    email: "karan.m@college.edu",
    semester: "5th Semester",
    branch: "Electronics",
    usn: "1DD23EC099",
    domain: "Graphics",
    workLink: "https://dribbble.com/karan_designs",
    status: "pending",
    submittedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    notes: "Branding and digital illustration background.",
  },
  {
    id: "req_seed_004",
    name: "Rohan Das",
    email: "rohan.d@college.edu",
    semester: "3rd Semester",
    branch: "Mechanical",
    usn: "1DD24ME034",
    domain: "Social Media",
    workLink: "https://instagram.com/rohan_visuals",
    status: "pending",
    submittedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: "req_seed_005",
    name: "Sneha Patil",
    email: "sneha.p@college.edu",
    semester: "3rd Semester",
    branch: "Computer Science",
    usn: "1DD24CS102",
    domain: "PR / Marketing & Sponsorship",
    workLink: "https://linkedin.com/in/snehapatil_pr",
    status: "pending",
    submittedAt: new Date(Date.now() - 3600000 * 36).toISOString(),
  },
  {
    id: "req_seed_006",
    name: "Vikas Gowda",
    email: "vikas.g@college.edu",
    semester: "5th Semester",
    branch: "Civil",
    usn: "1DD23CV044",
    domain: "Operations",
    workLink: "https://drive.google.com/file/d/sample-resume",
    status: "pending",
    submittedAt: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
];

export const SEED_EVENTS: ClubEvent[] = [
  {
    id: "event_seed_001",
    name: "Race to Innovate 2.0",
    description: "Anaadyanta Geekmayhem 2026 — 24-hour UI/UX & Creative Tech Hackathon. Compete in teams to solve real-world campus & product design challenges.",
    date: "March 20, 2026",
    time: "09:00 AM - 09:00 AM (24h)",
    location: "Main Auditorium & Design Lab",
    category: "Hackathon",
    status: "active",
    rsvpCount: 142,
    rsvpUids: ["admin_uid_jeevan", "mem_tech_praveen"],
    createdAt: "2026-08-20T10:00:00.000Z",
    createdBy: "admin_uid_jeevan",
  },
  {
    id: "event_seed_002",
    name: "UI/UX Masterclass: Glassmorphism & Neo-Brutalism",
    description: "Deep dive into atmospheric depth, lighting sources in dark mode, and crafting responsive design systems in Figma and React.",
    date: "April 12, 2026",
    time: "14:00 - 17:00",
    location: "Design Lab 404",
    category: "Workshop",
    status: "active",
    rsvpCount: 88,
    rsvpUids: ["mem_tech_praveen"],
    createdAt: "2026-08-22T14:30:00.000Z",
    createdBy: "admin_uid_jeevan",
  },
  {
    id: "event_seed_003",
    name: "Creative Coding Jam: Shaders & Three.js",
    description: "Hands-on session building generative 3D interactive graphics for modern websites.",
    date: "May 24, 2026",
    time: "16:00 - 19:00",
    location: "Computer Center 2",
    category: "Coding Jam",
    status: "active",
    rsvpCount: 64,
    rsvpUids: [],
    createdAt: "2026-08-25T08:00:00.000Z",
    createdBy: "admin_uid_jeevan",
  },
];

export const SEED_TODOS: Todo[] = [
  {
    id: "todo_seed_001",
    text: "Submit high-fidelity wireframes for Design Sprint v2",
    assignedTo: "admin_uid_jeevan",
    assignedToName: "Jeevan (Admin)",
    createdBy: "admin_uid_jeevan",
    createdByName: "Jeevan (Admin)",
    completed: false,
    dueDate: "Due Today, 11:59 PM",
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo_seed_002",
    text: "Setup Firebase Firestore collections & real-time sync",
    assignedTo: "mem_tech_praveen",
    assignedToName: "Praveen",
    createdBy: "admin_uid_jeevan",
    createdByName: "Jeevan (Admin)",
    completed: false,
    dueDate: "Due Tomorrow",
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo_seed_003",
    text: "Coordinate workshop setup in Design Lab 404",
    assignedTo: "mem_ops_rahul",
    assignedToName: "Rahul J",
    createdBy: "admin_uid_jeevan",
    createdByName: "Jeevan (Admin)",
    completed: false,
    dueDate: "March 15",
    createdAt: new Date().toISOString(),
  },
  {
    id: "todo_seed_004",
    text: "Design promotional banners for Race to Innovate 2.0",
    assignedTo: "mem_gfx_sarah",
    assignedToName: "Sarah Miller",
    createdBy: "admin_uid_jeevan",
    createdByName: "Jeevan (Admin)",
    completed: true,
    completedAt: new Date().toISOString(),
    dueDate: "Yesterday",
    createdAt: new Date().toISOString(),
  },
];
